version: '3.5'
services:
    api1: &api
        image: jnariai/rinha-backend-2024-q1-laravel:octane
        restart: always
        tty: true
        hostname: api1
        depends_on:
            db:
                condition: service_healthy
        environment:
            DB_HOST: db
            DB_DATABASE: "rinha"
            DB_USERNAME: "phpUser"
            DB_PASSWORD: "explode"
            APP_ENV: "prod"
            APP_NAME: "Rinha de backend"
        links:
            - db
        networks:
            - rinha-net
        deploy:
            resources:
                limits:
                    cpus: '0.4'
                    memory: '150MB'
    api2:
        <<: *api
    db:
        image: postgres:16.2-alpine3.19
        hostname: db
        restart: always
        tty: true
        environment:
            POSTGRES_PASSWORD: explode
            POSTGRES_USER: phpUser
            POSTGRES_DB: rinha
        volumes:
            - ./postgres/:/docker-entrypoint-initdb.d/
        ports:
            - "5432:5432"
        networks:
            - rinha-net
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: '200MB'
    nginx:
        image: nginx:1.25.3-alpine3.18
        restart: always
        tty: true
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api1
            - api2
        ports:
            - "9999:9999"
        networks:
            - rinha-net
        deploy:
            resources:
                limits:
                    cpus: '0.2'
                    memory: '50MB'
networks:
    rinha-net:
        driver: bridge
